name: Deploy to GKE

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      #comment
      # - name: Set GCP Credentials Environment Variable
      #   run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GCP_SA_KEY }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0
      
      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > infra/backend.tf << EOF
          terraform {
            backend "gcs" {
              bucket = "avi-hero-no-2"
              prefix = "terraform/state"
             }
            }
          EOF

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Force Unlock Terraform State (Manual Only)
        if: github.event_name == 'workflow_dispatch'
        run: terraform force-unlock -force <LOCK_ID>
        working-directory: infra

      - name: Plan Terraform -lock=false
        run: terraform plan
        working-directory: infra

      - name: Apply Terraform
        run: | 
          terraform apply -auto-approve
           -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
           -var="sql_password=${{ secrets.DB_PASSWORD }}"
        working-directory: infra

  build-and-deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --file user-service/pom.xml

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/your-gcp-project/user-service:latest ./user-service
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin gcr.io
          docker push gcr.io/your-gcp-project/user-service:latest

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials my-cluster --region us-central1
          kubectl apply -f k8s/deployment.yaml
